title: Artur Krrr
hero_text: Hi, I'm Artur 👋
hero_subtext: I'm a creative web developer who builds fast, clean, and beautiful websites.
email: artur@example.com

skills:
  - HTML & CSS
  - JavaScript (ES6+)
  - React
  - Git & GitHub
  - Responsive Design

projects:
  - title: Portfolio Site
    description: A responsive portfolio using HTML, CSS, JS, and Liquid on GitHub Pages.
  - title: Weather App
    description: Weather app using OpenWeather API with geolocation support.
  - title: Todo App
    description: A minimal task manager built with vanilla JS.
